### PR TITLE
Closes #11 Update r-cmd-check.yml

### LINKED ISSUE #11: Move R-CMD checks to 4.0, 4.1 and latest R version build
Move R-CMD checks to 4.0, 4.1 and latest R version build

### PR DESCRIPTION
**Pull request by bms63**

### CODE REVIEW

**Review by cicdguy — APPROVED** [review]
LGTM

**Comment by bms63** [comment]
Hey Dinakar,

I was trying to get our workflows updated to stop using 3.6 as a check.  Do I need to do anything additional in the admiral-core repo.  I see this in the repo for 3.6 which I'm unsure if this is doing anything??

image

**Comment by cicdguy** [comment]
> Hey Dinakar,
> 
> I was trying to get our workflows updated to stop using 3.6 as a check. Do I need to do anything additional in the admiral-core repo. I see this in the repo for 3.6 which I'm unsure if this is doing anything??
> 
> image

The `R_VERSION` environment variable needs to stay in sync with whichever version of R you are using in the `renv.lock` file. The dependencies for all workflows are included in the renv.lock file. So if you want to change the R version in the workflow, you'll need to also change the R version in the renv.lock file.

**Comment by bms63** [comment]
Shall I just wait on updating this until the common lock file has been implemented?

**Comment by cicdguy** [comment]
Yeah, let's wait just a bit more. Then we can safely upgrade.

**Pull request closed without merging**
