### PR TITLE
Remove renv and use cran latest

### PR DESCRIPTION
**Pull request by dgrassellyb**
- update docker images (build devel, latest and oldrel (4.3) from DESCRIPTION file + using latest CRAN repo) - note that there is a dependency with https://github.com/insightsengineering/r-image-creator/pull/18 
- update r-cmd checks matrix to use latest CRAN
- add workflow to check latest release on rocker/rstudio dockerhub tags
- upload docker images dependencies on admiralci release
- update other workflows using admiralci-latest
- setup script to install local dependencies (tested on a base image rocker/rstudio:latest)

### CODE REVIEW

**Review by bms63 — COMMENTED** [review]
Can we implement this after `1.0` is sent to CRAN.  We are very close (Monday or Tuesday I believe)

**Comment by dgrassellyb** [comment]
Could we proceed merging this one @cicdguy / @bms63 ?

**Review by bms63 — APPROVED** [review]
Let's see what happens!!

**Comment by dgrassellyb** [comment]
> Let's see what happens!!

(you can find here latest checks logs - https://github.com/pharmaverse/admiral/actions/runs/7553548756/job/20564562353 - and actually it worked also for devel ! 🕺)

**Pull request merged**
