### PR TITLE
27 template fail on warnings

### PR DESCRIPTION
**Pull request by bms63**

### CODE REVIEW

**Comment by bms63** [comment]
@cicdguy  Hey Dinakar.  Sorry wanted to bring this to your attention as well in our meeting today. 

I was trying to get the templates to fail when warnings are detected  As we are deprecating functions I want to make sure those deprecated functions don't appear in our templates.  We deprecrate functions first with a warning and then with an error, which means functions can stay in the templates for multiple releases before we notice them failing.

I can inject `option=2` into the file, but I am a little stuck on getting this set up correctly.  I feel like there is an easier way.

**Comment by bms63** [comment]
Hey @cicdguy.  I removed vanilla and updated with suggest profile change, but looks like it is not elevating the warning to an error.  

Any ideas?

**Comment by bms63** [comment]
> > Hey @cicdguy. I removed vanilla and updated with suggest profile change, but looks like it is not elevating the warning to an error.
> > Any ideas?
> 
> [89d7e11](https://github.com/pharmaverse/admiralci/commit/89d7e11c99b2927aad4fa8a1e997561a88aa2366) might help.

Nice!  Testing out in here https://github.com/pharmaverse/admiral/pull/1677

**Comment by ddsjoberg** [comment]
@bms63 @cicdguy awesome! clever use of the Rprofile.

It looks like it should work from my review. If it were me, I would merge and do some testing. @cicdguy is there a better way to test this, though? Perhaps create a PR that we do not intend to merge into admiral where we add a warning into a template file. We then update the workflow to reference this branch of admiralci?

**Pull request closed without merging**
