### PR TITLE
Update pkgdown.yml

### PR DESCRIPTION
**Pull request by dgrassellyb**

### CODE REVIEW

**Comment by dgrassellyb** [comment]
> Previously, the website only published when we did a release. When I upversioned to major for `1.0` the website published rather than staying at `0.12.3`.
> 
> Is there anyway to keep the publish website only on release option?

We can for sure update the workflows to trigger the publication only on releases event, but i think you want also to see updates on devel version right ? 

Screenshot 2023-12-13 at 14 48 44

for now we're having this condition, on main and patch branch : 
`if: github.event_name == 'push' || startsWith(github.ref, 'refs/tags/v')`, should we add a condition to check if we have a dev version (pattern x.y.z.9000) instead of push trigger ?

**Comment by bms63** [comment]
I was expecting the behavior to be as following:

- An official github release triggers the building of the main website (1.0.0, 1.0.1, etc).  If there is no official release, then the website stays as is.   So it should be 0.12.3
- The dev website continuously exists with the X.Y.Z.ABC increments, so as soon as the CRAN submission is completed and we do a github release and we increment in main branch then the dev website would have 1.0.0.900.

Apologies if this isn't super clear!!  @bundfussr any additional thoughts?

**Comment by bms63** [comment]
> > I was expecting the behavior to be as following:
> > 
> > * An official github release triggers the building of the main website (1.0.0, 1.0.1, etc).  If there is no official release, then the website stays as is.   So it should be 0.12.3
> > * The dev website continuously exists with the X.Y.Z.ABC increments, so as soon as the CRAN submission is completed and we do a github release and we increment in main branch then the dev website would have 1.0.0.900.
> > 
> > Apologies if this isn't super clear!! @bundfussr any additional thoughts?
> 
> In principle, this would be the cleanest solution. However, in the past this caused some issues. For example, if the new website is not build when the package is submitted and there are links to new pages, e.g., a new vignette, the CRAN link checker fails. So maybe it is easier to build the website when submitting to CRAN (even if this may confuse some users in the period from CRAN submission to release).

I agree that publishing the website as we submit to CRAN is nice to had off any broken links and the time is so minimal (usually). I'm not sure why `1.0` is taking so long for CRAN to approve, but hopefully in the future the turnaround is faster.  

So to just keep it easy.  When I increment to a major/minor/patch version for a CRAN submission we will just have the website publish from `main`.  We will no longer need the github release to trigger publication of the website.  `dev` stuff stays the same.  

Is that okay with everyone?  Apologies for the back and forth in a merged PR!

**Comment by bundfussr** [comment]
> > > I was expecting the behavior to be as following:
> > > 
> > > * An official github release triggers the building of the main website (1.0.0, 1.0.1, etc).  If there is no official release, then the website stays as is.   So it should be 0.12.3
> > > * The dev website continuously exists with the X.Y.Z.ABC increments, so as soon as the CRAN submission is completed and we do a github release and we increment in main branch then the dev website would have 1.0.0.900.
> > > 
> > > Apologies if this isn't super clear!! @bundfussr any additional thoughts?
> > 
> > 
> > In principle, this would be the cleanest solution. However, in the past this caused some issues. For example, if the new website is not build when the package is submitted and there are links to new pages, e.g., a new vignette, the CRAN link checker fails. So maybe it is easier to build the website when submitting to CRAN (even if this may confuse some users in the period from CRAN submission to release).
> 
> I agree that publishing the website as we submit to CRAN is nice to had off any broken links and the time is so minimal (usually). I'm not sure why `1.0` is taking so long for CRAN to approve, but hopefully in the future the turnaround is faster.
> 
> So to just keep it easy. When I increment to a major/minor/patch version for a CRAN submission we will just have the website publish from `main`. We will no longer need the github release to trigger publication of the website. `dev` stuff stays the same.
> 
> Is that okay with everyone? Apologies for the back and forth in a merged PR!

The github release should trigger the creation of the vx.y.z folder in gh-pages.

**Comment by bms63** [comment]
Ah okay - so just leave everything pretty as is then??

**Comment by bundfussr** [comment]
> Ah okay - so just leave everything pretty as is then??

Yes

**Comment by bms63** [comment]
image

**Pull request merged**
